"""fix proposal-proposal_topics circular FK

Revision ID: 05948c96ce34
Revises: 4fef3d0b9c1d
Create Date: 2026-09-11 13:53:13.120555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05948c96ce34'
down_revision: Union[str, Sequence[str], None] = '4fef3d0b9c1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
