"""add photo_url and theme_preference to users

Revision ID: 39a4216ef589
Revises: 2cd80ee88503
Create Date: 2026-09-10 13:10:31.216843

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "39a4216ef589"
down_revision: Union[str, Sequence[str], None] = "2cd80ee88503"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("photo_url", sa.String(length=500), nullable=True))
    op.add_column(
        "users",
        sa.Column(
            "theme_preference",
            sa.String(length=10),
            nullable=False,
            server_default="light",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "theme_preference")
    op.drop_column("users", "photo_url")
    # ### end Alembic commands ###
