"""add supervisor, supervisor_preferences, group interested area and assigned supervisor

Revision ID: 3a020a921ef1
Revises: b17a82c5652b
Create Date: 2026-09-10 08:37:23.896919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a020a921ef1'
down_revision: Union[str, Sequence[str], None] = 'b17a82c5652b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
