"""add proposal resubmission deadline and direct assignment

Revision ID: 4f438ed0b4e7
Revises: 59e339f4dbc4
Create Date: 2026-09-11 08:27:56.301946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f438ed0b4e7'
down_revision: Union[str, Sequence[str], None] = '59e339f4dbc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
