"""add student profile with department level term section

Revision ID: 59e339f4dbc4
Revises: 3034c93dd247
Create Date: 2026-09-11 08:27:44.989559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59e339f4dbc4'
down_revision: Union[str, Sequence[str], None] = '3034c93dd247'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposal_topics', sa.Column('assigned_by_supervisor', sa.Boolean(), nullable=False))
    op.alter_column('proposal_topics', 'file_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.add_column('proposals', sa.Column('resubmission_deadline', sa.DateTime(), nullable=True))
    op.add_column('proposals', sa.Column('suggested_area', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposals', 'suggested_area')
    op.drop_column('proposals', 'resubmission_deadline')
    op.alter_column('proposal_topics', 'file_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_column('proposal_topics', 'assigned_by_supervisor')
    # ### end Alembic commands ###
