"""hash verification codes + rate limiting

Revision ID: 783e3a88a7cb
Revises: d2d049c8620b
Create Date: 2026-09-13 20:02:06.263593

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "783e3a88a7cb"
down_revision: Union[str, Sequence[str], None] = "d2d049c8620b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "verification_attempts", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "users", sa.Column("verification_locked_until", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "verification_locked_until")
    op.drop_column("users", "verification_attempts")
    # ### end Alembic commands ###
