"""add department to supervisor

Revision ID: a9a31e2f856c
Revises: 4f438ed0b4e7
Create Date: 2026-09-11 08:40:10.386129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9a31e2f856c'
down_revision: Union[str, Sequence[str], None] = '4f438ed0b4e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supervisors', sa.Column('department', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supervisors', 'department')
    # ### end Alembic commands ###
