"""add category to thesis for project vs thesis distinction

Revision ID: d260bef389d9
Revises: 3247fcf80e59
Create Date: 2026-09-11 09:01:50.843705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd260bef389d9'
down_revision: Union[str, Sequence[str], None] = '3247fcf80e59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('theses', sa.Column('category', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('theses', 'category')
    # ### end Alembic commands ###
