"""add verification code fields

Revision ID: ecf8d87f816a
Revises: c109cf1ff5d8
Create Date: 2026-09-10 08:03:32.291283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecf8d87f816a'
down_revision: Union[str, Sequence[str], None] = 'c109cf1ff5d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_code', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('verification_code_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_code_expires_at')
    op.drop_column('users', 'verification_code')
    # ### end Alembic commands ###
