"""add created_at to users for unverified account cleanup

Revision ID: f1f4d6c93c96
Revises: 0f1535fb3371
Create Date: 2026-09-13 18:57:16.156234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1f4d6c93c96'
down_revision: Union[str, Sequence[str], None] = '0f1535fb3371'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
